#ifndef KSU_DATE_PART_HEADER

#define KSU_DATE_PART_HEADER

#define KSU_DATE_PART_NOT_FOUND	-1
#define KSU_DATE_PART_CENTURY	  0
#define KSU_DATE_PART_DAY	  1
#define KSU_DATE_PART_DAY_HOUR	  2
#define KSU_DATE_PART_DAY_MINUTE	  3
#define KSU_DATE_PART_DAY_SECOND	  4
#define KSU_DATE_PART_DAYOFYEAR	  5
#define KSU_DATE_PART_DECADE	  6
#define KSU_DATE_PART_EPOCH	  7
#define KSU_DATE_PART_HOUR	  8
#define KSU_DATE_PART_HOUR_MINUTE	  9
#define KSU_DATE_PART_HOUR_SECOND	 10
#define KSU_DATE_PART_ISOWEEK	 11
#define KSU_DATE_PART_ISOWEEKDAY	 12
#define KSU_DATE_PART_ISOYEAR	 13
#define KSU_DATE_PART_JULIAN_NUM	 14
#define KSU_DATE_PART_MILLENNIUM	 15
#define KSU_DATE_PART_MINUTE	 16
#define KSU_DATE_PART_MINUTE_SECOND	 17
#define KSU_DATE_PART_MONTH	 18
#define KSU_DATE_PART_MONTHABBREV	 19
#define KSU_DATE_PART_MONTHNAME	 20
#define KSU_DATE_PART_QUARTER	 21
#define KSU_DATE_PART_SECOND	 22
#define KSU_DATE_PART_SECONDS_IN_DAY	 23
#define KSU_DATE_PART_WEEK	 24
#define KSU_DATE_PART_WEEKDAY	 25
#define KSU_DATE_PART_WEEKDAYABBREV	 26
#define KSU_DATE_PART_WEEKDAYNAME	 27
#define KSU_DATE_PART_YEAR	 28
#define KSU_DATE_PART_YEAR_MONTH	 29

#define KSU_DATE_PART_COUNT	30

extern int   ksu_date_part_search(char *w);
extern char *ksu_date_part_keyword(int code);

#endif
